"""empty message

Revision ID: 0ad22fbe128f
Revises: 832b60f506e7
Create Date: 2023-02-26 15:36:30.317403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ad22fbe128f'
down_revision = '832b60f506e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('outstanding', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('due', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blocks', schema=None) as batch_op:
        batch_op.drop_column('due')
        batch_op.drop_column('outstanding')
        batch_op.drop_column('paid')

    # ### end Alembic commands ###
