"""empty message

Revision ID: 2f925417440f
Revises: 80a5889b7918
Create Date: 2023-02-04 17:58:53.494971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f925417440f'
down_revision = '80a5889b7918'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room_type', schema=None) as batch_op:
        batch_op.alter_column('range',
               existing_type=sa.FLOAT(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room_type', schema=None) as batch_op:
        batch_op.alter_column('range',
               existing_type=sa.String(),
               type_=sa.FLOAT(),
               existing_nullable=True)

    # ### end Alembic commands ###
