"""empty message

Revision ID: 7a52e26e3286
Revises: 0ad22fbe128f
Create Date: 2023-02-26 17:55:01.452267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a52e26e3286'
down_revision = '0ad22fbe128f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occupant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roomCost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('amountPaid', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occupant', schema=None) as batch_op:
        batch_op.drop_column('amountPaid')
        batch_op.drop_column('roomCost')

    # ### end Alembic commands ###
