"""empty message

Revision ID: 832b60f506e7
Revises: 8c511f1c7e56
Create Date: 2023-02-13 21:52:42.452362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '832b60f506e7'
down_revision = '8c511f1c7e56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occupant', schema=None) as batch_op:
        batch_op.alter_column('paid',
               existing_type=sa.VARCHAR(),
               type_=sa.Boolean(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occupant', schema=None) as batch_op:
        batch_op.alter_column('paid',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
