"""empty message

Revision ID: 8c511f1c7e56
Revises: b5f1e9ec4f0f
Create Date: 2023-02-05 13:33:00.162306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c511f1c7e56'
down_revision = 'b5f1e9ec4f0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occupant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('occupant', schema=None) as batch_op:
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
